version: "3.8"

services:

  ms-config-server:
    build: ./config-server
    container_name: config-server
    environment: # Active profile NATIVE. Related to SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS
      #SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS: file:/app/config-repo, file:/app/config-repo/{application}
    networks:
      - desire-mgmt-network
    ports:
      - "8888:8888"
    restart: on-failure:3
    
  ms-eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - desire-mgmt-network
    ports:
      - "8761:8761"
    restart: on-failure:3
    depends_on:
      - ms-config-server
  
  ms-api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - desire-mgmt-network
    ports:
      - "8080:8080"
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-products-apirest
      - ms-orders-apirest
      - ms-customers-apirest
  
  ms-prometheus-server:
    image: prom/prometheus:latest
    container_name: prometheus-server
    volumes:
      - ./prometheus/config:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    networks:
      - desire-mgmt-network
    ports:
      - "9090:9090"
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-products-db      
      - ms-products-apirest
      - ms-orders-db
      - ms-orders-apirest
      - ms-customers-db
      - ms-customers-apirest      
  
  ms-grafana-server:
    image: grafana/grafana:latest
    container_name: grafana-server 
    user: '0'
    volumes:
      - ./grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/3662_rev2.json:/etc/grafana/provisioning/dashboards/3662_rev2.json
      - ./grafana/dashboards/prometheus_stats.json:/etc/grafana/provisioning/dashboards/prometheus_stats.json
      - grafana_storage01:/var/lib/grafana
      - grafana_storage02:/etc/grafana 
    networks:
      - desire-mgmt-network
    ports:
      - "3000:3000"    
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-products-db      
      - ms-products-apirest
      - ms-orders-db
      - ms-orders-apirest
      - ms-customers-db
      - ms-customers-apirest    
      - ms-prometheus-server    
          
  ms-products-db:
    image: postgres:latest
    container_name: postgresdb01
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: productsDb
    networks:
      - desire-mgmt-network
    ports:
      - "5432:5432"
     
  ms-orders-db:
    image: postgres:latest
    container_name: postgresdb02
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: ordersDb
    networks:
      - desire-mgmt-network
    ports:
      - "5433:5432"
      
  ms-customers-db:
    image: postgres:latest
    container_name: postgresdb03
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: customersDb
    networks:
      - desire-mgmt-network
    ports:
      - "5434:5432"
           
  ms-products-apirest:
    build: ./ms-products
    container_name: ms-products
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - desire-mgmt-network
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-products-db
      
  ms-orders-apirest:
    build:  ./ms-orders
    container_name: ms-orders
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - desire-mgmt-network
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-orders-db
  
  ms-customers-apirest:
    build: ./ms-customers
    container_name: ms-customers
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - desire-mgmt-network
    restart: on-failure:3
    depends_on:
      - ms-config-server
      - ms-eureka-server
      - ms-customers-db
          
networks:
  desire-mgmt-network:

volumes:
  grafana_storage01: {}
  grafana_storage02: {}
  
    
    