INSERT INTO orders(customer_id,order_date,creation_timestamp,update_timestamp) 
VALUES(2,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(4,CURRENT_DATE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO order_details(quantity, discount, product_id,creation_timestamp,update_timestamp, order_id)
VALUES(88,2.3,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1),
(8,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1),
(3,3,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1),
(24,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1),
(13,0,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,2),
(44,20,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,2),
(9,0,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,2),
(8,0,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,3),
(2,0.3,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,3),
(16,0.7,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,3),
(1,0,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,4),
(1,0,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,4),
(12,0.7,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,5),
(4,0,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,6),
(4,0,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,6);