
spring:
  datasource:
    url: jdbc:postgresql://ms-products-db:5432/productsDb   
        
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


info:
  app:
    profile: prod 