
global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: config-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']
      
  - job_name: eureka-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
      
# Static discover of some microservices
 # - job_name: api-gateway
  #  metrics_path: '/actuator/prometheus'
   # static_configs:
    #  - targets: ['api-gateway:8080']
      
  #- job_name: apirest
   # metrics_path: '/actuator/prometheus'
    #static_configs:
     # - targets: ['ms-products:7701', 'ms-orders:7702', 'ms-customers:7703']
  
 # Dynamic disover of some microservices with Eureka 
  - job_name: 'eureka-dynamic-scrape'
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
    relabel_configs:
    - action: replace
      replacement: '/actuator/prometheus'
      target_label: __metrics_path__
        