global:
  scrape_interval: 15s


scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus-server:9090"]
      
  - job_name: config-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']
      
  - job_name: eureka-server
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']
         
  - job_name: api-gateway
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
      
  - job_name: apirest
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-products:7701', 'ms-orders:7702', 'ms-customers:7703']
        