# Main settings
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ordersDb
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    # Defer data.sql until Spring loads
    defer-datasource-initialization: true
  sql:
    init:
    # For any script-based initialization
      mode: always
  
# ms-product name in eureka-server 
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      
# Enable /actuator/info
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
        
# Basic data for /actuator/info
info:
  app:
    name: ms-orders
    version: 1.0.0
    profile: default

ms-products:
  url: http://localhost:7701

    