
spring:
  datasource:
    url: jdbc:postgresql://ms-orders-db:5432/ordersDb   
        
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


info:
  app:
    profile: prod
    
