
spring:
  datasource:
    url: jdbc:postgresql://postgresdb02:5432/ordersDb   
        
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


info:
  app:
    profile: prod
    
ms-products:
  url: http://ms-products:7701
ms-customers:
  url: http://ms-customers:7703