# Main settings
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          default-label: main
        # config-server in local
        native:
        # search conf files in the app path
          searchLocations: config-repo, config-repo/{application}
  profiles:
  # config-server in local active
    active: native    
server:
  port: 8888 
     
management:
  endpoint:
    health:
      probes:
        enabled: true  
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
            
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus     
        
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    profile: default
    author: Ivan
    web: https://github.com/Ivan-Montes
    
    