
info:
  app:
    profile: dev
        
management:
  endpoints:
    web:
      exposure:
        include: "*" 
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always  